// Auto-generated smart test combinations
// Generated: 2025-08-07T14:17:47.219Z
//
// 📊 Smart Test Suite Analysis
// ============================
//
// Total Combinations: 31
// Estimated Duration: 4 minutes
//
// By Category:
// - Critical: 9 tests (29%)
// - Common: 6 tests (19%)
// - Edge Cases: 5 tests (16%)
// - Experimental: 3 tests (10%)
// - Random: 8 tests (26%)
//
// By Technology:
// - TypeScript: 24 tests
// - JavaScript: 7 tests
// - Full-Stack: 20 tests
// - Frontend-Only: 4 tests
//
// Recommended Test Orders:
// 1. Quick Smoke Test: Run 'critical' tests (9 tests, ~1 min)
// 2. Standard CI: Run 'critical' + 'common' (15 tests, ~2 min)
// 3. Full Regression: Run all tests (31 tests, ~4 min)
//

export const SMART_TEST_COMBINATIONS = {
  critical: [
    {
      framework: "react",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-frontend-only",
      category: "critical",
      expectedDuration: 5000,
    },
    {
      framework: "react",
      backend: "express",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-express-postgres",
      category: "critical",
      expectedDuration: 8000,
    },
    {
      framework: "react",
      backend: "nestjs",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-nestjs-postgres",
      category: "critical",
      expectedDuration: 9000,
    },
    {
      framework: "next",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "next-frontend-only",
      category: "critical",
      expectedDuration: 6000,
    },
    {
      framework: "next",
      backend: "next-api",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "next-fullstack",
      category: "critical",
      expectedDuration: 8000,
    },
    {
      framework: "vue",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "vue-frontend-only",
      category: "critical",
      expectedDuration: 5000,
    },
    {
      framework: "vue",
      backend: "fastify",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "vue-fastify-postgres",
      category: "critical",
      expectedDuration: 8000,
    },
    {
      framework: "react",
      backend: "hono",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-hono-edge",
      category: "critical",
      expectedDuration: 7000,
    },
    {
      framework: "svelte",
      backend: "fastify",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "svelte-fastify-postgres",
      category: "critical",
      expectedDuration: 8000,
    },
  ],
  common: [
    {
      framework: "react",
      backend: "express",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "node",
      typescript: false,
      name: "react-express-js",
      category: "common",
      expectedDuration: 6000,
    },
    {
      framework: "vue",
      backend: "express",
      database: "mongodb",
      orm: "none",
      styling: "scss",
      runtime: "node",
      typescript: false,
      name: "vue-express-mongodb-js",
      category: "common",
      expectedDuration: 7000,
    },
    {
      framework: "next",
      backend: "koa",
      database: "mongodb",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "next-koa-mongodb",
      category: "common",
      expectedDuration: 8000,
    },
    {
      framework: "react",
      backend: "express",
      database: "mysql",
      orm: "drizzle",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-express-mysql-drizzle",
      category: "common",
      expectedDuration: 8000,
    },
    {
      framework: "remix",
      backend: "express",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "remix-express-postgres",
      category: "common",
      expectedDuration: 8000,
    },
    {
      framework: "astro",
      backend: "express",
      database: "postgres",
      orm: "drizzle",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "astro-express-postgres",
      category: "common",
      expectedDuration: 8000,
    },
  ],
  edge: [
    {
      framework: "vanilla",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "node",
      typescript: false,
      name: "vanilla-minimal",
      category: "edge",
      expectedDuration: 4000,
    },
    {
      framework: "vanilla",
      backend: "node",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "node",
      typescript: false,
      name: "vanilla-node-backend",
      category: "edge",
      expectedDuration: 5000,
    },
    {
      framework: "solid",
      backend: "hono",
      database: "postgres",
      orm: "drizzle",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "solid-hono-postgres",
      category: "edge",
      expectedDuration: 9000,
    },
    {
      framework: "svelte",
      backend: "koa",
      database: "mysql",
      orm: "typeorm",
      styling: "scss",
      runtime: "node",
      typescript: true,
      name: "svelte-koa-mysql-typeorm",
      category: "edge",
      expectedDuration: 9000,
    },
    {
      framework: "react",
      backend: "fastify",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-fastify-api-only",
      category: "edge",
      expectedDuration: 6000,
    },
  ],
  experimental: [
    {
      framework: "solid",
      backend: "hono",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "solid-hono-experimental",
      category: "experimental",
      expectedDuration: 7000,
    },
    {
      framework: "astro",
      backend: "hono",
      database: "postgres",
      orm: "drizzle",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "astro-hono-drizzle",
      category: "experimental",
      expectedDuration: 9000,
    },
    {
      framework: "angular",
      backend: "nestjs",
      database: "postgres",
      orm: "typeorm",
      styling: "scss",
      runtime: "node",
      typescript: true,
      name: "angular-nestjs-typeorm",
      category: "experimental",
      expectedDuration: 10000,
    },
  ],
  random: [
    {
      framework: "next",
      backend: "hono",
      database: "none",
      orm: "none",
      styling: "styled-components",
      runtime: "node",
      typescript: true,
      name: "random-next-hono-none-0",
      category: "experimental",
      expectedDuration: 8915.323708681255,
    },
    {
      framework: "nuxt",
      backend: "express",
      database: "none",
      orm: "none",
      styling: "scss",
      runtime: "node",
      typescript: true,
      name: "random-nuxt-express-none-1",
      category: "experimental",
      expectedDuration: 9125.070088088387,
    },
    {
      framework: "solid",
      backend: "koa",
      database: "firebase",
      orm: "prisma",
      styling: "css",
      runtime: "bun",
      typescript: true,
      name: "random-solid-koa-firebase-2",
      category: "experimental",
      expectedDuration: 6968.285533883449,
    },
    {
      framework: "svelte",
      backend: "koa",
      database: "postgres",
      orm: "prisma",
      styling: "css",
      runtime: "node",
      typescript: false,
      name: "random-svelte-koa-postgres-3",
      category: "experimental",
      expectedDuration: 7403.343418570046,
    },
    {
      framework: "vite",
      backend: "nestjs",
      database: "postgres",
      orm: "drizzle",
      styling: "css",
      runtime: "bun",
      typescript: false,
      name: "random-vite-nestjs-postgres-4",
      category: "experimental",
      expectedDuration: 7929.937717539415,
    },
    {
      framework: "vue",
      backend: "node",
      database: "firebase",
      orm: "typeorm",
      styling: "scss",
      runtime: "bun",
      typescript: true,
      name: "random-vue-node-firebase-5",
      category: "experimental",
      expectedDuration: 9456.004022204848,
    },
    {
      framework: "next",
      backend: "node",
      database: "postgres",
      orm: "none",
      styling: "styled-components",
      runtime: "deno",
      typescript: false,
      name: "random-next-node-postgres-6",
      category: "experimental",
      expectedDuration: 7703.697178086044,
    },
    {
      framework: "next",
      backend: "node",
      database: "mongodb",
      orm: "typeorm",
      styling: "tailwind",
      runtime: "deno",
      typescript: true,
      name: "random-next-node-mongodb-7",
      category: "experimental",
      expectedDuration: 9620.03651102569,
    },
  ],
  all: [
    {
      framework: "react",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-frontend-only",
      category: "critical",
      expectedDuration: 5000,
    },
    {
      framework: "react",
      backend: "express",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-express-postgres",
      category: "critical",
      expectedDuration: 8000,
    },
    {
      framework: "react",
      backend: "nestjs",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-nestjs-postgres",
      category: "critical",
      expectedDuration: 9000,
    },
    {
      framework: "next",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "next-frontend-only",
      category: "critical",
      expectedDuration: 6000,
    },
    {
      framework: "next",
      backend: "next-api",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "next-fullstack",
      category: "critical",
      expectedDuration: 8000,
    },
    {
      framework: "vue",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "vue-frontend-only",
      category: "critical",
      expectedDuration: 5000,
    },
    {
      framework: "vue",
      backend: "fastify",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "vue-fastify-postgres",
      category: "critical",
      expectedDuration: 8000,
    },
    {
      framework: "react",
      backend: "hono",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-hono-edge",
      category: "critical",
      expectedDuration: 7000,
    },
    {
      framework: "svelte",
      backend: "fastify",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "svelte-fastify-postgres",
      category: "critical",
      expectedDuration: 8000,
    },
    {
      framework: "react",
      backend: "express",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "node",
      typescript: false,
      name: "react-express-js",
      category: "common",
      expectedDuration: 6000,
    },
    {
      framework: "vue",
      backend: "express",
      database: "mongodb",
      orm: "none",
      styling: "scss",
      runtime: "node",
      typescript: false,
      name: "vue-express-mongodb-js",
      category: "common",
      expectedDuration: 7000,
    },
    {
      framework: "next",
      backend: "koa",
      database: "mongodb",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "next-koa-mongodb",
      category: "common",
      expectedDuration: 8000,
    },
    {
      framework: "react",
      backend: "express",
      database: "mysql",
      orm: "drizzle",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-express-mysql-drizzle",
      category: "common",
      expectedDuration: 8000,
    },
    {
      framework: "remix",
      backend: "express",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "remix-express-postgres",
      category: "common",
      expectedDuration: 8000,
    },
    {
      framework: "astro",
      backend: "express",
      database: "postgres",
      orm: "drizzle",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "astro-express-postgres",
      category: "common",
      expectedDuration: 8000,
    },
    {
      framework: "vanilla",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "node",
      typescript: false,
      name: "vanilla-minimal",
      category: "edge",
      expectedDuration: 4000,
    },
    {
      framework: "vanilla",
      backend: "node",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "node",
      typescript: false,
      name: "vanilla-node-backend",
      category: "edge",
      expectedDuration: 5000,
    },
    {
      framework: "solid",
      backend: "hono",
      database: "postgres",
      orm: "drizzle",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "solid-hono-postgres",
      category: "edge",
      expectedDuration: 9000,
    },
    {
      framework: "svelte",
      backend: "koa",
      database: "mysql",
      orm: "typeorm",
      styling: "scss",
      runtime: "node",
      typescript: true,
      name: "svelte-koa-mysql-typeorm",
      category: "edge",
      expectedDuration: 9000,
    },
    {
      framework: "react",
      backend: "fastify",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-fastify-api-only",
      category: "edge",
      expectedDuration: 6000,
    },
    {
      framework: "solid",
      backend: "hono",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "solid-hono-experimental",
      category: "experimental",
      expectedDuration: 7000,
    },
    {
      framework: "astro",
      backend: "hono",
      database: "postgres",
      orm: "drizzle",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "astro-hono-drizzle",
      category: "experimental",
      expectedDuration: 9000,
    },
    {
      framework: "angular",
      backend: "nestjs",
      database: "postgres",
      orm: "typeorm",
      styling: "scss",
      runtime: "node",
      typescript: true,
      name: "angular-nestjs-typeorm",
      category: "experimental",
      expectedDuration: 10000,
    },
    {
      framework: "next",
      backend: "hono",
      database: "none",
      orm: "none",
      styling: "styled-components",
      runtime: "node",
      typescript: true,
      name: "random-next-hono-none-0",
      category: "experimental",
      expectedDuration: 8915.323708681255,
    },
    {
      framework: "nuxt",
      backend: "express",
      database: "none",
      orm: "none",
      styling: "scss",
      runtime: "node",
      typescript: true,
      name: "random-nuxt-express-none-1",
      category: "experimental",
      expectedDuration: 9125.070088088387,
    },
    {
      framework: "solid",
      backend: "koa",
      database: "firebase",
      orm: "prisma",
      styling: "css",
      runtime: "bun",
      typescript: true,
      name: "random-solid-koa-firebase-2",
      category: "experimental",
      expectedDuration: 6968.285533883449,
    },
    {
      framework: "svelte",
      backend: "koa",
      database: "postgres",
      orm: "prisma",
      styling: "css",
      runtime: "node",
      typescript: false,
      name: "random-svelte-koa-postgres-3",
      category: "experimental",
      expectedDuration: 7403.343418570046,
    },
    {
      framework: "vite",
      backend: "nestjs",
      database: "postgres",
      orm: "drizzle",
      styling: "css",
      runtime: "bun",
      typescript: false,
      name: "random-vite-nestjs-postgres-4",
      category: "experimental",
      expectedDuration: 7929.937717539415,
    },
    {
      framework: "vue",
      backend: "node",
      database: "firebase",
      orm: "typeorm",
      styling: "scss",
      runtime: "bun",
      typescript: true,
      name: "random-vue-node-firebase-5",
      category: "experimental",
      expectedDuration: 9456.004022204848,
    },
    {
      framework: "next",
      backend: "node",
      database: "postgres",
      orm: "none",
      styling: "styled-components",
      runtime: "deno",
      typescript: false,
      name: "random-next-node-postgres-6",
      category: "experimental",
      expectedDuration: 7703.697178086044,
    },
    {
      framework: "next",
      backend: "node",
      database: "mongodb",
      orm: "typeorm",
      styling: "tailwind",
      runtime: "deno",
      typescript: true,
      name: "random-next-node-mongodb-7",
      category: "experimental",
      expectedDuration: 9620.03651102569,
    },
  ],
};

export default SMART_TEST_COMBINATIONS;
