// Auto-generated smart test combinations
// Generated: 2025-08-05T23:13:41.818Z
//
// 📊 Smart Test Suite Analysis
// ============================
//
// Total Combinations: 30
// Estimated Duration: 4 minutes
//
// By Category:
// - Critical: 9 tests (30%)
// - Common: 6 tests (20%)
// - Edge Cases: 5 tests (17%)
// - Experimental: 3 tests (10%)
// - Random: 7 tests (23%)
//
// By Technology:
// - TypeScript: 24 tests
// - JavaScript: 6 tests
// - Full-Stack: 16 tests
// - Frontend-Only: 6 tests
//
// Recommended Test Orders:
// 1. Quick Smoke Test: Run 'critical' tests (9 tests, ~1 min)
// 2. Standard CI: Run 'critical' + 'common' (15 tests, ~2 min)
// 3. Full Regression: Run all tests (30 tests, ~4 min)
//

export const SMART_TEST_COMBINATIONS = {
  critical: [
    {
      framework: "react",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-frontend-only",
      category: "critical",
      expectedDuration: 5000,
    },
    {
      framework: "react",
      backend: "express",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-express-postgres",
      category: "critical",
      expectedDuration: 8000,
    },
    {
      framework: "react",
      backend: "nestjs",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-nestjs-postgres",
      category: "critical",
      expectedDuration: 9000,
    },
    {
      framework: "next",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "next-frontend-only",
      category: "critical",
      expectedDuration: 6000,
    },
    {
      framework: "next",
      backend: "next-api",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "next-fullstack",
      category: "critical",
      expectedDuration: 8000,
    },
    {
      framework: "vue",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "vue-frontend-only",
      category: "critical",
      expectedDuration: 5000,
    },
    {
      framework: "vue",
      backend: "fastify",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "vue-fastify-postgres",
      category: "critical",
      expectedDuration: 8000,
    },
    {
      framework: "react",
      backend: "hono",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-hono-edge",
      category: "critical",
      expectedDuration: 7000,
    },
    {
      framework: "svelte",
      backend: "fastify",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "svelte-fastify-postgres",
      category: "critical",
      expectedDuration: 8000,
    },
  ],
  common: [
    {
      framework: "react",
      backend: "express",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "node",
      typescript: false,
      name: "react-express-js",
      category: "common",
      expectedDuration: 6000,
    },
    {
      framework: "vue",
      backend: "express",
      database: "mongodb",
      orm: "none",
      styling: "scss",
      runtime: "node",
      typescript: false,
      name: "vue-express-mongodb-js",
      category: "common",
      expectedDuration: 7000,
    },
    {
      framework: "next",
      backend: "koa",
      database: "mongodb",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "next-koa-mongodb",
      category: "common",
      expectedDuration: 8000,
    },
    {
      framework: "react",
      backend: "express",
      database: "mysql",
      orm: "drizzle",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-express-mysql-drizzle",
      category: "common",
      expectedDuration: 8000,
    },
    {
      framework: "remix",
      backend: "express",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "remix-express-postgres",
      category: "common",
      expectedDuration: 8000,
    },
    {
      framework: "astro",
      backend: "express",
      database: "postgres",
      orm: "drizzle",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "astro-express-postgres",
      category: "common",
      expectedDuration: 8000,
    },
  ],
  edge: [
    {
      framework: "vanilla",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "node",
      typescript: false,
      name: "vanilla-minimal",
      category: "edge",
      expectedDuration: 4000,
    },
    {
      framework: "vanilla",
      backend: "node",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "node",
      typescript: false,
      name: "vanilla-node-backend",
      category: "edge",
      expectedDuration: 5000,
    },
    {
      framework: "solid",
      backend: "hono",
      database: "postgres",
      orm: "drizzle",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "solid-hono-postgres",
      category: "edge",
      expectedDuration: 9000,
    },
    {
      framework: "svelte",
      backend: "koa",
      database: "mysql",
      orm: "typeorm",
      styling: "scss",
      runtime: "node",
      typescript: true,
      name: "svelte-koa-mysql-typeorm",
      category: "edge",
      expectedDuration: 9000,
    },
    {
      framework: "react",
      backend: "fastify",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-fastify-api-only",
      category: "edge",
      expectedDuration: 6000,
    },
  ],
  experimental: [
    {
      framework: "solid",
      backend: "hono",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "solid-hono-experimental",
      category: "experimental",
      expectedDuration: 7000,
    },
    {
      framework: "astro",
      backend: "hono",
      database: "postgres",
      orm: "drizzle",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "astro-hono-drizzle",
      category: "experimental",
      expectedDuration: 9000,
    },
    {
      framework: "angular",
      backend: "nestjs",
      database: "postgres",
      orm: "typeorm",
      styling: "scss",
      runtime: "node",
      typescript: true,
      name: "angular-nestjs-typeorm",
      category: "experimental",
      expectedDuration: 10000,
    },
  ],
  random: [
    {
      framework: "vanilla",
      backend: "express",
      database: "none",
      orm: "none",
      styling: "scss",
      runtime: "bun",
      typescript: true,
      name: "random-vanilla-express-none-0",
      category: "experimental",
      expectedDuration: 9767.079386319143,
    },
    {
      framework: "react",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "node",
      typescript: true,
      name: "random-react-none-none-1",
      category: "experimental",
      expectedDuration: 7435.977573371268,
    },
    {
      framework: "angular",
      backend: "nestjs",
      database: "mysql",
      orm: "typeorm",
      styling: "scss",
      runtime: "cloudflare-workers",
      typescript: true,
      name: "random-angular-nestjs-mysql-2",
      category: "experimental",
      expectedDuration: 6256.931792512595,
    },
    {
      framework: "solid",
      backend: "nestjs",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "bun",
      typescript: true,
      name: "random-solid-nestjs-none-3",
      category: "experimental",
      expectedDuration: 7167.877697725802,
    },
    {
      framework: "svelte",
      backend: "express",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "vercel-edge",
      typescript: false,
      name: "random-svelte-express-none-5",
      category: "experimental",
      expectedDuration: 6861.758800236668,
    },
    {
      framework: "next",
      backend: "fastify",
      database: "mongodb",
      orm: "prisma",
      styling: "styled-components",
      runtime: "vercel-edge",
      typescript: true,
      name: "random-next-fastify-mongodb-6",
      category: "experimental",
      expectedDuration: 8747.565431702515,
    },
    {
      framework: "remix",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "vercel-edge",
      typescript: false,
      name: "random-remix-none-none-7",
      category: "experimental",
      expectedDuration: 6022.453228291222,
    },
  ],
  all: [
    {
      framework: "react",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-frontend-only",
      category: "critical",
      expectedDuration: 5000,
    },
    {
      framework: "react",
      backend: "express",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-express-postgres",
      category: "critical",
      expectedDuration: 8000,
    },
    {
      framework: "react",
      backend: "nestjs",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-nestjs-postgres",
      category: "critical",
      expectedDuration: 9000,
    },
    {
      framework: "next",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "next-frontend-only",
      category: "critical",
      expectedDuration: 6000,
    },
    {
      framework: "next",
      backend: "next-api",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "next-fullstack",
      category: "critical",
      expectedDuration: 8000,
    },
    {
      framework: "vue",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "vue-frontend-only",
      category: "critical",
      expectedDuration: 5000,
    },
    {
      framework: "vue",
      backend: "fastify",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "vue-fastify-postgres",
      category: "critical",
      expectedDuration: 8000,
    },
    {
      framework: "react",
      backend: "hono",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-hono-edge",
      category: "critical",
      expectedDuration: 7000,
    },
    {
      framework: "svelte",
      backend: "fastify",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "svelte-fastify-postgres",
      category: "critical",
      expectedDuration: 8000,
    },
    {
      framework: "react",
      backend: "express",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "node",
      typescript: false,
      name: "react-express-js",
      category: "common",
      expectedDuration: 6000,
    },
    {
      framework: "vue",
      backend: "express",
      database: "mongodb",
      orm: "none",
      styling: "scss",
      runtime: "node",
      typescript: false,
      name: "vue-express-mongodb-js",
      category: "common",
      expectedDuration: 7000,
    },
    {
      framework: "next",
      backend: "koa",
      database: "mongodb",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "next-koa-mongodb",
      category: "common",
      expectedDuration: 8000,
    },
    {
      framework: "react",
      backend: "express",
      database: "mysql",
      orm: "drizzle",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-express-mysql-drizzle",
      category: "common",
      expectedDuration: 8000,
    },
    {
      framework: "remix",
      backend: "express",
      database: "postgres",
      orm: "prisma",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "remix-express-postgres",
      category: "common",
      expectedDuration: 8000,
    },
    {
      framework: "astro",
      backend: "express",
      database: "postgres",
      orm: "drizzle",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "astro-express-postgres",
      category: "common",
      expectedDuration: 8000,
    },
    {
      framework: "vanilla",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "node",
      typescript: false,
      name: "vanilla-minimal",
      category: "edge",
      expectedDuration: 4000,
    },
    {
      framework: "vanilla",
      backend: "node",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "node",
      typescript: false,
      name: "vanilla-node-backend",
      category: "edge",
      expectedDuration: 5000,
    },
    {
      framework: "solid",
      backend: "hono",
      database: "postgres",
      orm: "drizzle",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "solid-hono-postgres",
      category: "edge",
      expectedDuration: 9000,
    },
    {
      framework: "svelte",
      backend: "koa",
      database: "mysql",
      orm: "typeorm",
      styling: "scss",
      runtime: "node",
      typescript: true,
      name: "svelte-koa-mysql-typeorm",
      category: "edge",
      expectedDuration: 9000,
    },
    {
      framework: "react",
      backend: "fastify",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "react-fastify-api-only",
      category: "edge",
      expectedDuration: 6000,
    },
    {
      framework: "solid",
      backend: "hono",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "solid-hono-experimental",
      category: "experimental",
      expectedDuration: 7000,
    },
    {
      framework: "astro",
      backend: "hono",
      database: "postgres",
      orm: "drizzle",
      styling: "tailwind",
      runtime: "node",
      typescript: true,
      name: "astro-hono-drizzle",
      category: "experimental",
      expectedDuration: 9000,
    },
    {
      framework: "angular",
      backend: "nestjs",
      database: "postgres",
      orm: "typeorm",
      styling: "scss",
      runtime: "node",
      typescript: true,
      name: "angular-nestjs-typeorm",
      category: "experimental",
      expectedDuration: 10000,
    },
    {
      framework: "vanilla",
      backend: "express",
      database: "none",
      orm: "none",
      styling: "scss",
      runtime: "bun",
      typescript: true,
      name: "random-vanilla-express-none-0",
      category: "experimental",
      expectedDuration: 9767.079386319143,
    },
    {
      framework: "react",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "node",
      typescript: true,
      name: "random-react-none-none-1",
      category: "experimental",
      expectedDuration: 7435.977573371268,
    },
    {
      framework: "angular",
      backend: "nestjs",
      database: "mysql",
      orm: "typeorm",
      styling: "scss",
      runtime: "cloudflare-workers",
      typescript: true,
      name: "random-angular-nestjs-mysql-2",
      category: "experimental",
      expectedDuration: 6256.931792512595,
    },
    {
      framework: "solid",
      backend: "nestjs",
      database: "none",
      orm: "none",
      styling: "tailwind",
      runtime: "bun",
      typescript: true,
      name: "random-solid-nestjs-none-3",
      category: "experimental",
      expectedDuration: 7167.877697725802,
    },
    {
      framework: "svelte",
      backend: "express",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "vercel-edge",
      typescript: false,
      name: "random-svelte-express-none-5",
      category: "experimental",
      expectedDuration: 6861.758800236668,
    },
    {
      framework: "next",
      backend: "fastify",
      database: "mongodb",
      orm: "prisma",
      styling: "styled-components",
      runtime: "vercel-edge",
      typescript: true,
      name: "random-next-fastify-mongodb-6",
      category: "experimental",
      expectedDuration: 8747.565431702515,
    },
    {
      framework: "remix",
      backend: "none",
      database: "none",
      orm: "none",
      styling: "css",
      runtime: "vercel-edge",
      typescript: false,
      name: "random-remix-none-none-7",
      category: "experimental",
      expectedDuration: 6022.453228291222,
    },
  ],
};

export default SMART_TEST_COMBINATIONS;
