name: Publish CLI Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (beta, latest)'
        required: true
        default: 'beta'
        type: choice
        options:
          - beta
          - latest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        working-directory: packages/cli
        
      - name: Run type checking
        run: bun run typecheck
        working-directory: packages/cli
        
      - name: Run linting
        run: bun run lint
        working-directory: packages/cli
        
      - name: Run tests
        run: bun run test
        working-directory: packages/cli

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        working-directory: packages/cli
        
      - name: Build package
        run: bun run build
        working-directory: packages/cli
        
      - name: Publish to npm (beta)
        if: github.event.inputs.tag == 'beta' || contains(github.ref, 'beta')
        run: npm publish --tag beta
        working-directory: packages/cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Publish to npm (latest)
        if: github.event.inputs.tag == 'latest' || (github.ref_type == 'tag' && !contains(github.ref, 'beta'))
        run: npm publish
        working-directory: packages/cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}