name: Test CLI Package

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 21]
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        working-directory: packages/cli
        
      - name: Run type checking
        run: bun run typecheck
        working-directory: packages/cli
        
      - name: Run linting
        run: bun run lint
        working-directory: packages/cli
        
      - name: Run tests
        run: bun run test
        working-directory: packages/cli
        
      - name: Test CLI functionality
        run: |
          bun run build
          node dist/cli.js --version
          node dist/cli.js init test-app --framework=react --backend=none --database=none --orm=none --styling=css --no-git --yes
          ls -la test-app/
        working-directory: packages/cli