import { FaShieldAlt, FaExclamationTriangle, FaCogs, FaFileContract } from "react-icons/fa";
import { Link } from "react-router-dom";

import { LegalPageLayout, LegalSection, ContactSection } from "@/components/legal";
import { APP_NAME } from "@/config/constants";

export function TermsOfServicePage() {
  return (
    <LegalPageLayout
      title={`${APP_NAME} TERMS OF SERVICE`}
      description={`Legal terms and conditions for using ${APP_NAME} CLI and related services`}
      icon={<FaFileContract className="h-16 w-16 text-comic-red" />}
      iconColor="bg-comic-red"
      titleColor="text-comic-red"
    >
      {/* Acceptance Section */}
      <LegalSection
        icon={<FaShieldAlt className="h-8 w-8 text-comic-blue" />}
        title="1. ACCEPTANCE OF TERMS"
        iconColor="text-comic-blue"
      >
        <div className="space-y-4">
          <p className="font-comic text-lg text-comic-darkBlue leading-relaxed">
            By downloading, installing, or using the {APP_NAME} CLI tool (&quot;Service&quot;), you
            agree to be bound by these Terms of Service (&quot;Terms&quot;). If you disagree with
            any part of these terms, you may not use our Service.
          </p>
          <p className="font-comic text-lg text-comic-darkBlue leading-relaxed">
            These Terms apply to all users of the Service, including but not limited to developers,
            organizations, and automated systems.
          </p>
        </div>
      </LegalSection>

      {/* Service Description */}
      <LegalSection
        icon={<FaCogs className="h-8 w-8 text-comic-purple" />}
        title="2. DESCRIPTION OF SERVICE"
        iconColor="text-comic-purple"
        delay={0.1}
      >
        <div className="space-y-4">
          <p className="font-comic text-lg text-comic-darkBlue leading-relaxed">
            {APP_NAME} is a command-line interface (CLI) tool designed to scaffold and generate web
            application projects. The Service includes:
          </p>
          <ul className="font-comic text-lg text-comic-darkBlue leading-relaxed ml-8 space-y-2">
            <li>• Project generation and scaffolding tools</li>
            <li>• Framework and library integration</li>
            <li>• Template and boilerplate code generation</li>
            <li>• Configuration file management</li>
            <li>• Anonymous usage analytics collection</li>
          </ul>
        </div>
      </LegalSection>

      {/* Disclaimer - Big Warning Panel */}
      <LegalSection
        icon={<FaExclamationTriangle className="h-8 w-8 text-comic-red" />}
        title="3. DISCLAIMER & LIABILITY"
        iconColor="text-comic-red"
        delay={0.2}
      >
        <div className="flex items-center mb-6">
          <div className="ml-auto bg-comic-red text-comic-white px-4 py-2 rounded-full font-comic font-bold text-lg transform rotate-3">
            IMPORTANT!
          </div>
        </div>

        <div className="space-y-6">
          <div className="bg-comic-red text-comic-white p-6 rounded-lg border-4 border-comic-black">
            <h3 className="font-comic text-2xl font-bold mb-4">NO WARRANTIES</h3>
            <p className="font-comic text-lg leading-relaxed">
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT
              WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
              IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
              NON-INFRINGEMENT.
            </p>
          </div>

          <div className="bg-comic-white p-6 rounded-lg border-4 border-comic-red">
            <h3 className="font-comic text-2xl font-bold text-comic-red mb-4">
              PRODUCTION ENVIRONMENT DISCLAIMER
            </h3>
            <p className="font-comic text-lg text-comic-darkBlue leading-relaxed mb-4">
              <strong>YOU ACKNOWLEDGE AND AGREE THAT:</strong>
            </p>
            <ul className="font-comic text-lg text-comic-darkBlue leading-relaxed ml-6 space-y-2">
              <li>
                • {APP_NAME} generates code and configurations that may not be suitable for all
                production environments
              </li>
              <li>
                • You are solely responsible for testing, validating, and securing any code
                generated by {APP_NAME} before deployment
              </li>
              <li>
                • Generated code may contain security vulnerabilities, performance issues, or
                compatibility problems
              </li>
              <li>
                • You must perform adequate security audits, performance testing, and quality
                assurance before production use
              </li>
            </ul>
          </div>

          <div className="bg-comic-black text-comic-white p-6 rounded-lg border-4 border-comic-red">
            <h3 className="font-comic text-2xl font-bold mb-4">LIMITATION OF LIABILITY</h3>
            <p className="font-comic text-lg leading-relaxed mb-4">
              <strong>
                {APP_NAME.toUpperCase()} AND ITS AFFILIATES SHALL NOT BE LIABLE FOR ANY:
              </strong>
            </p>
            <ul className="font-comic text-lg leading-relaxed ml-6 space-y-2">
              <li>• Direct, indirect, incidental, special, consequential, or punitive damages</li>
              <li>• Loss of profits, revenue, data, or business opportunities</li>
              <li>• Production outages, system failures, or data breaches</li>
              <li>• Security vulnerabilities in generated code</li>
              <li>• Damages resulting from use of third-party dependencies or frameworks</li>
              <li>• Any damages exceeding $100 USD in aggregate</li>
            </ul>
          </div>
        </div>
      </LegalSection>

      {/* User Responsibilities */}
      <LegalSection
        icon={<FaShieldAlt className="h-8 w-8 text-comic-green" />}
        title="4. USER RESPONSIBILITIES"
        iconColor="text-comic-green"
        delay={0.3}
      >
        <div className="space-y-4">
          <p className="font-comic text-lg text-comic-darkBlue leading-relaxed">
            You are responsible for:
          </p>
          <ul className="font-comic text-lg text-comic-darkBlue leading-relaxed ml-8 space-y-2">
            <li>• Ensuring compatibility of generated code with your target environment</li>
            <li>• Implementing proper security measures for any generated applications</li>
            <li>• Testing generated code thoroughly before production deployment</li>
            <li>• Maintaining backups of your projects and data</li>
            <li>• Complying with all applicable laws and regulations</li>
            <li>• Respecting third-party licenses of generated dependencies</li>
          </ul>
        </div>
      </LegalSection>

      {/* Data Collection */}
      <LegalSection
        icon={<FaCogs className="h-8 w-8 text-comic-blue" />}
        title="5. DATA COLLECTION & ANALYTICS"
        iconColor="text-comic-blue"
        delay={0.4}
      >
        <div className="space-y-4">
          <p className="font-comic text-lg text-comic-darkBlue leading-relaxed">
            By using {APP_NAME}, you consent to our collection of anonymous usage analytics
            including:
          </p>
          <ul className="font-comic text-lg text-comic-darkBlue leading-relaxed ml-8 space-y-2">
            <li>• Framework and technology selections</li>
            <li>• Command usage patterns</li>
            <li>• Error rates and performance metrics</li>
            <li>• Generated project characteristics (anonymized)</li>
          </ul>
          <p className="font-comic text-lg text-comic-darkBlue leading-relaxed">
            This data helps us improve the tool and identify common issues. No personally
            identifiable information, source code, or sensitive project details are collected. You
            may opt out by setting the{" "}
            <code className="bg-comic-gray px-2 py-1 rounded font-mono">
              TELEMETRY_DISABLED=true
            </code>{" "}
            environment variable.
          </p>
          <div className="bg-comic-yellow p-4 rounded-lg border-4 border-comic-black">
            <p className="font-comic text-lg text-comic-darkBlue">
              For more details, see our{" "}
              <Link to="/legal/privacy" className="text-comic-red font-bold hover:underline">
                Privacy Policy
              </Link>
              .
            </p>
          </div>
        </div>
      </LegalSection>

      {/* Third-Party Services */}
      <LegalSection
        icon={<FaCogs className="h-8 w-8 text-comic-purple" />}
        title="6. THIRD-PARTY SERVICES AND DEPENDENCIES"
        iconColor="text-comic-purple"
        delay={0.5}
      >
        <div className="space-y-4">
          <p className="font-comic text-lg text-comic-darkBlue leading-relaxed">
            {APP_NAME} integrates with and generates code using various third-party services,
            frameworks, and libraries. Your use of generated code may be subject to additional terms
            from:
          </p>
          <ul className="font-comic text-lg text-comic-darkBlue leading-relaxed ml-8 space-y-2">
            <li>• Framework providers (React, Vue, Angular, etc.)</li>
            <li>• Database providers (PostgreSQL, MongoDB, etc.)</li>
            <li>• Authentication services (Auth0, Firebase, etc.)</li>
            <li>• Hosting and deployment platforms</li>
            <li>• NPM and other package registries</li>
          </ul>
          <p className="font-comic text-lg text-comic-darkBlue leading-relaxed">
            We are not responsible for the availability, security, or terms of these third-party
            services.
          </p>
        </div>
      </LegalSection>

      {/* Intellectual Property */}
      <LegalSection
        icon={<FaFileContract className="h-8 w-8 text-comic-green" />}
        title="7. INTELLECTUAL PROPERTY"
        iconColor="text-comic-green"
        delay={0.6}
      >
        <div className="space-y-4">
          <p className="font-comic text-lg text-comic-darkBlue leading-relaxed">
            Code generated by {APP_NAME} is provided to you under the MIT License. You own the
            generated code and may use it for any purpose, subject to the licenses of included
            dependencies.
          </p>
          <p className="font-comic text-lg text-comic-darkBlue leading-relaxed">
            The {APP_NAME} CLI tool itself and associated documentation remain the intellectual
            property of {APP_NAME} and its contributors.
          </p>
        </div>
      </LegalSection>

      {/* Contact Section */}
      <ContactSection delay={0.7} emailType="LEGAL" title="CONTACT US" />
    </LegalPageLayout>
  );
}
