import { Github, ExternalLink, Terminal } from "lucide-react";

/**
 * Footer component - Brutalist terminal-style footer
 */
export function Footer() {
  return (
    <footer className="footer">
      <div className="footer-content">
        <div className="footer-inner">
          {/* Terminal prompt */}
          <div className="footer-prompt">
            <Terminal size={16} className="icon-primary" />
            <span className="prompt-symbol">$</span>
            <span className="prompt-text"></span>
            <span className="prompt-cursor">_</span>
          </div>

          {/* Links */}
          <div className="footer-links">
            <a
              href="https://precast.dev"
              target="_blank"
              rel="noopener noreferrer"
              className="footer-link"
            >
              <span>[PRECAST.DEV]</span>
              <ExternalLink size={12} className="link-icon" />
            </a>
            <a
              href="https://github.com/BuunGroupCore/precast-app"
              target="_blank"
              rel="noopener noreferrer"
              className="footer-link"
            >
              <Github size={14} />
              <span>[SOURCE]</span>
            </a>
          </div>
        </div>

        {/* Status bar */}
        <div className="status-bar">
          <div className="status-left">
            <span>
              STATUS: <span className="status-value">ONLINE</span>
            </span>
            <span>
              MODE: <span className="status-value">DEV</span>
            </span>
            <span>
              VERSION: <span className="status-value">1.0.0</span>
            </span>
          </div>
          <div className="status-right">
            GENERATED BY <span className="status-value">PRECAST CLI</span>
          </div>
        </div>
      </div>
    </footer>
  );
}
