name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-website:
    name: Test Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run type check
        run: bun run typecheck
        working-directory: packages/website

      - name: Install Playwright browsers
        run: bunx playwright install --with-deps chromium firefox
        working-directory: packages/website

      - name: Run Playwright tests
        run: bun run test
        working-directory: packages/website

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/website/playwright-report/
          retention-days: 30

  test-cli:
    name: Test CLI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run CLI tests
        run: bun run test:ci
        working-directory: packages/cli

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cli-test-results-node-${{ matrix.node-version }}
          path: packages/cli/reports/
          retention-days: 30

  test-integration:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: [test-cli]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build CLI
        run: bun run build
        working-directory: packages/cli

      - name: Test create-precast-app
        run: |
          # Create a test project
          node packages/cli/dist/index.js test-project \
            --framework=react \
            --backend=node \
            --database=postgres \
            --orm=prisma \
            --styling=tailwind \
            --docker \
            --no-git

          # Verify project was created
          test -f test-project/package.json
          test -f test-project/Dockerfile
          test -f test-project/docker-compose.yml
          
          # Clean up
          rm -rf test-project

      - name: Test incompatible configuration
        run: |
          # This should fail - Angular requires TypeScript
          ! node packages/cli/dist/index.js test-invalid \
            --framework=angular \
            --no-typescript \
            --no-git