name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-cli:
    name: Test CLI Package
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.1
          run_install: false
          
      - name: Verify pnpm installation
        run: |
          which pnpm
          pnpm --version
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build shared packages
        run: |
          echo "Building UI package..."
          pnpm --filter @precast/ui run build
          echo "Verifying UI build..."
          ls -la packages/ui/dist/
        
      - name: Build CLI
        run: pnpm --filter @precast/cli run build
        
      - name: Run type checking
        run: pnpm --filter @precast/cli run typecheck
        
      - name: Run linting
        run: pnpm --filter @precast/cli run lint
        
      - name: Run unit tests
        run: pnpm --filter @precast/cli test tests/unit
        timeout-minutes: 5
        
      - name: Run integration tests (critical)
        run: cd packages/cli && pnpm test tests/integration/project-quality.test.ts
        timeout-minutes: 10
        
      - name: Run Docker tests
        run: cd packages/cli && pnpm test tests/integration/docker-deployment.test.ts
        timeout-minutes: 5
        
        
      - name: Run PowerUps tests
        run: cd packages/cli && pnpm test tests/integration/powerups.test.ts
        timeout-minutes: 5
        
      - name: Run edge case tests
        run: cd packages/cli && pnpm test tests/integration/edge-cases.test.ts
        timeout-minutes: 5
        
      - name: Generate test report
        if: always()
        run: |
          if [ -f "TEST_REPORT.md" ]; then
            echo "## Test Report Summary" >> $GITHUB_STEP_SUMMARY
            cat TEST_REPORT.md >> $GITHUB_STEP_SUMMARY
          fi
        working-directory: packages/cli
        
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cli-test-report-node${{ matrix.node-version }}
          path: packages/cli/TEST_REPORT.md
          retention-days: 7
          
      - name: Check for leftover test directories
        if: always()
        run: |
          leftover=$(ls -la /tmp/ | grep precast-test- | wc -l)
          if [ "$leftover" -gt 0 ]; then
            echo "⚠️ Found $leftover leftover test directories"
            ls -la /tmp/ | grep precast-test-
            exit 1
          else
            echo "✅ No leftover test directories found"
          fi

