name: Update PostHog Analytics Data

# Security: This workflow is restricted to only modify files in the data/ directory
# - Path validation prevents writing outside data/ directory
# - File validation only allows posthog-analytics.json and posthog-analytics.csv
# - Git operations are limited to data/ directory files only
# - Minimal permissions granted to workflow

on:
  schedule:
    # Run every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main
    paths:
      - "scripts/fetch-posthog-analytics.js"
      - ".github/workflows/update-posthog-analytics.yml"

jobs:
  fetch-analytics:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: read
      checks: none
      deployments: none
      issues: none
      packages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Fetch PostHog Analytics Data
        env:
          POSTHOG_PROJECT_ID: ${{ secrets.POSTHOG_PROJECT_ID }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          POSTHOG_HOST: ${{ secrets.POSTHOG_HOST }}
        run: node scripts/fetch-posthog-analytics.js

      - name: Check for changes in data directory only
        id: verify-changed
        run: |
          # Only check for changes in data/ directory
          if git diff --quiet data/; then
            echo "No changes in data directory"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in data directory"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Verify only data files are modified
        if: steps.verify-changed.outputs.changed == 'true'
        run: |
          # Get list of modified files
          MODIFIED_FILES=$(git diff --name-only)
          echo "Modified files: $MODIFIED_FILES"

          # Check if any files outside data/ directory are modified
          if echo "$MODIFIED_FILES" | grep -v '^data/' | grep -q .; then
            echo "❌ Error: Files outside data/ directory were modified!"
            echo "Modified files outside data/:"
            echo "$MODIFIED_FILES" | grep -v '^data/' || true
            exit 1
          fi

          echo "✅ All modifications are within data/ directory"

      - name: Commit and push analytics data
        if: steps.verify-changed.outputs.changed == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Only add PostHog analytics files from data/ directory
          git add data/posthog-analytics.json data/posthog-analytics.csv

          # Verify staging area only contains data/ files
          STAGED_FILES=$(git diff --cached --name-only)
          echo "Staged files: $STAGED_FILES"

          if echo "$STAGED_FILES" | grep -v '^data/' | grep -q .; then
            echo "❌ Error: Attempted to stage files outside data/ directory!"
            git reset
            exit 1
          fi

          git commit -m "📊 Update PostHog analytics data [skip ci]"
          git push

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: posthog-analytics-data
          path: |
            data/posthog-analytics.json
            data/posthog-analytics.csv
          retention-days: 90